mysite/enquetes/urls.py
from django.urls import path

from . import views

app_name = "enquetes"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detalhe"),
    path("<int:pk>/resultado/", views.ResultsView.as_view(), name="resultado"),
    path("<int:pergunta_id>/voto/", views.voto, name="voto"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("enquetes/", include("enquetes.urls")),
    path("admin/", admin.site.urls),
]

mysite/enquetes/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin


import datetime

class Pergunta(models.Model):
    texto_pergunta = models.CharField(max_length=200)
    data_pub = models.DateTimeField("data publicada")

    def __str__(self):
        return self.texto_pergunta
    
    @admin.display(
        boolean=True,
        ordering="data_pub",
        description="Publicado recentemente?",
    )

    def foi_publicado_recentemente(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.data_pub <= now


class Escolha(models.Model):
    question = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/enquetes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Escolha, Pergunta

# Create your views here.

class IndexView(generic.ListView):
    template_name = "enquetes/index.html"
    context_object_name = "lista_perguntas_recentes"

    def get_queryset(self):

        """
        Return the last five published questions (not including those set to be published in the future).
        """

        return Pergunta.objects.filter(data_pub__lte=timezone.now()).order_by("-data_pub")[:5]


class DetailView(generic.DetailView):

    model = Pergunta
    template_name = "enquetes/detalhe.html"

    def get_queryset(self):
        """
        Exclui quaisquer perguntas que não foram publicadas ainda.
        """
        return Pergunta.objects.filter(data_pub__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Pergunta
    template_name = "enquetes/resultado.html"


def voto(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    try:
        escolha_selecionada = pergunta.escolha_set.get(pk=request.POST["escolha"])
    except (KeyError, Escolha.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "enquetes/detalhe.html",
            {
                "pergunta": pergunta,
                "error_message": "Você não escolheu uma resposta.",
            },
        )
    else:
        escolha_selecionada.votes += 1
        escolha_selecionada.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("enquetes:resultado", args=(pergunta.id,)))

mysite/enquetes/templates/enquetes/detalhe.html
<h1>{{ pergunta.texto_pergunta }}</h1>
<ul>
{% for escolha in pergunta.escolha_set.all %}
    <li>{{ escolha.choice_text }}</li>
{% endfor %}
</ul>

<form action="{% url 'enquetes:voto' pergunta.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ pergunta.pergunta_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for escolha in pergunta.escolha_set.all %}
            <input type="radio" name="escolha" id="escolha{{ forloop.counter }}" value="{{ escolha.id }}">
            <label for="escolha{{ forloop.counter }}">{{ escolha.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Voto">
    </form>

mysite/enquetes/templates/enquetes/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'enquetes/style.css' %}">

{% if lista_perguntas_recentes %}
    <ul>
    {% for pergunta in lista_perguntas_recentes %}
    <li><a href="{% url 'enquetes:detalhe' pergunta.id %}">{{ pergunta.texto_pergunta }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Não há enquetes disponíveis.</p>
{% endif %}

mysite/enquetes/templates/enquetes/resultado.html
<h1>{{ pergunta.texto_pergunta }}</h1>

<ul>
{% for escolha in pergunta.escolha_set.all %}
    <li>{{ escolha.choice_text }} -- {{ escolha.votes }} voto{{ escolha.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'enquetes:detalhe' pergunta.id %}">Votar novamente?</a>